### ISSUE TITLE
Cannot dynamically create an instance of a record 

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/dotnetcore-canvas#16]
When creating unit test for an application. Data needs to be faked. But not all data is needed to be filled for a test to succeed. The records however required this. 

Also, due to the structure of these records, a workaround is needed to work with these records and [Faker](https://github.com/bchavez/Bogus). Resulting in the following [mess](https://github.com/tpcly/epsilon-lti/blob/6919d931ce793314bd1928c1c04177236e4961f4/Epsilon.UnitTest/TestDataGeneratorCanvasResponse.cs)

 When using the following faker snippet:

```c#
        return new Faker<EnrollmentTerm>().RuleFor(static f => f.Id, static f => f.Random.String())
            .RuleFor(static f => f.Name, static f => f.Random.String())
            .RuleFor(static f => f.StartAt, static f => f.Date.Past())
            .RuleFor(static f => f.EndAt, static f => f.Date.Soon(80, f.Date.Past()));
``` 
the following error occurs:
`Cannot dynamically create an instance of type 'Tpcly.Canvas.Abstractions.GraphQl.EnrollmentTerm'. Reason: No parameterless constructor defined.`

However, the faker snippet is preferd for a good clean code base. 

Any suggestions?

**Comment by Typiqally** [comment]
Basically all required parameters should be in the constructor, and all the nullables should be properties in this case. In any case, Bogus does not support parameterless constructor automatically, requiring your configuration. Seems like this package solves it, but I haven't checked how to use it yet: https://github.com/nickdodd79/AutoBogus.

**Comment by NealGeilen** [comment]
Yes, the suggestion fixes the problem. 
However, it results in new issue due to the circular data structure. 
It tries to fill ever tying that it is in the records. Resulting in endless data generation. 

The options given in the package don't seem to work. 
With the combination of the last update of the package, I am going to look at another solution.
